# Generated by Django 4.0.4 on 2022-06-05 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='hodnoceni',
            field=models.IntegerField(help_text='Ohodnoťte album', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hodnocení'),
        ),
        migrations.AlterField(
            model_name='pisen',
            name='poradi',
            field=models.IntegerField(help_text='Zadejte pořadí stopy', verbose_name='Pořadí stopy'),
        ),
    ]
