# Generated by Django 4.0.4 on 2022-06-05 19:29

import alba.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0002_alter_album_hodnoceni_alter_pisen_poradi'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=alba.models.poster_path, verbose_name='Náhledový obrázek'),
        ),
    ]
