# Generated by Django 4.0.4 on 2022-06-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0003_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='runtime',
            field=models.TimeField(null=True, verbose_name='Délka alba'),
        ),
    ]
